### ISSUE TITLE
UnboundLocalError: local variable 'node_uri' referenced before assignment

### ISSUE THREAD

**Issue by zvowell** [mjordan/islandora_workbench#223]
With paged content, using subdirectories (following the steps here: https://mjordan.github.io/islandora_workbench_docs/paged_and_compound/), I'm running into an error. The check looks like this:

    OK, connection to Drupal at http://localhost:8000 verified.
    OK, configuration file has all required values (did not check for optional values).
    OK, CSV file testBatch_02_clean/barneberg_forTesting_004_bookObjects-minimal.csv found.
    OK, all 5 rows in the CSV file have the same number of columns as there are headers (16).
    OK, CSV column headers match Drupal field names.
    OK, required Drupal fields are present in the CSV file.
    OK, ETDF field values in the CSV file validate.
    OK, term IDs/names in CSV file exist in their respective taxonomies.
    OK, page directories are all present.
    Configuration and input data appear to be valid.

But when I run workbench without --check, a node is initially created, but then an error occurs:

    OK, connection to Drupal at http://localhost:8000 verified.
    Node for "Letter from Shepherd to Barneberg, March 10, 1927" (record 3) created at http://localhost:8000/node/113.
    Traceback (most recent call last):
      File "./workbench", line 963, in <module>
        create()
      File "./workbench", line 357, in create
        create_children_from_directory(
      File "/mnt/c/Users/zvowell/Documents/islandora_workbench/workbench_utils.py", line 2680, in create_children_from_directory
        config, page_file_path, node_uri, fake_csv_record)
    UnboundLocalError: local variable 'node_uri' referenced before assignment

The csv I'm using is here: https://gist.github.com/zvowell/b1e513ef408dc4124990721724ba0bd0
And the directory and file names can be seen here: https://gist.github.com/zvowell/19925967f31da0a1ca07ab99ef5e8bef

The config file is:

    task: create
    host: "http://localhost:8000"
    username: admin
    password: islandora
    input_dir: testBatch_02_clean
    input_csv: barneberg_forTesting_004_bookObjects-minimal.csv
    allow_adding_terms: true
    paged_content_from_directories: true
    paged_content_page_model_tid: 29

Of possible interest, when I first tried workbench with paged content from subdirectories, I received a different error ("TypeError: argument of type 'bool' is not iterable"), and no node was created. The csv for that first try had many more records, and included some entity reference fields. But I'm not sure why that should result in a different error? Let me know if it'd be helpful to paste that error in this issue, or open another issue. (If the latter, I'll wait until this issue is resolved, before opening a new one). Thank you!

**Comment by mjordan** [comment]
@zvowell did your workbench.log show that the page node didn't get created? If it is created, `node_uri` should be defined at https://github.com/mjordan/islandora_workbench/blob/main/workbench_utils.py#L2653. The block starting at https://github.com/mjordan/islandora_workbench/blob/main/workbench_utils.py#L2677 should not be executed unless the request to create the page returns a `201`. I'll fix that, but wanted to confirm this is what happened to you.

**Comment by mjordan** [comment]
With commit 86b8894be751d3fa05724d1065760fe05dd7f33a I've rearranged the media creation code so it only fires if the page/child node was successful. Integration test for creating paged content from directories passes so I pushed this change to the `main` branch. Thanks for pointing out the problem.

If you can pull down the latest changes to `main` and try running Workbench again and let me know that the pages were created (or not), I'd appreciate it.

(note that the second link ^^ no longer points to the intended place because I moved that block of code.)

**Comment by zvowell** [comment]
@mjordan here's what the log said about the page (right after the message saying the Paged Content node (the parent) was successfully created):
    WARNING - Node for page "3_rekl_36_OBJ-001" not created, HTTP response code was 422.

I'm going to pull down the changes now, and will let you know the results. Thanks!

**Comment by mjordan** [comment]
Yeah, that's consistent with `node_uri` not being populated (it's the missing page node's URI that should be in that variable). Thanks for letting me know. I hope the fix works for you.

**Comment by zvowell** [comment]
okay, the fix worked for the node creation, but I'm still getting the 422 message for the pages. I'm going to try this on a fresh VM and see if that doesn't help. (I think I may have tampered with the VM I've been using when I tried to expand the disk storage).

**Comment by mjordan** [comment]
Good to hear that worked, but would you mind adding "log_json: true" to your config and trying again? Your log will contain the JSON that is pushed up to Drupal to create nodes. It might show why those pages are failing.

**Comment by zvowell** [comment]
here's the log for a successful paged content node (so weird to not be calling this a "book object"!), and the first page node that fails, with "log_json: true" enabled:

    18-Feb-21 09:20:15 - INFO - {'type': [{'target_id': 'islandora_object', 'target_type': 'node_type'}], 'title': [{'value': 'California School for the Deaf Response to CA Library Inventory Survey'}], 'status': [{'value': 1}], 'field_collection_name': [{'value': 'Grace E. Barneberg Papers'}], 'field_display_hints': [{'target_id': '2', 'target_type': 'taxonomy_term'}], 'field_collection_id': [{'value': 'MS0002'}], 'field_model': [{'target_id': '28', 'target_type': 'taxonomy_term'}], 'field_member_of': [{'target_id': '48', 'target_type': 'node_type'}], 'field_edtf_date_issued': [{'value': '2015-07-20'}], 'field_edtf_date_modified': [{'value': '2017-08-11'}], 'field_islandoraseven_pid': [{'value': 'rekl:101'}], 'field_folder': [{'value': '17'}], 'field_description': [{'value': 'Part of CA State Hospital Library Inventory Survey documenting the need for books and educational materials in the California hospital, prison, and institution systems.'}], 'field_box': [{'value': '1'}], 'field_local_identifier': [{'value': '002-2-b-01-17-08'}]}
    18-Feb-21 09:20:17 - INFO - Node for California School for the Deaf Response to CA Library Inventory Survey (record 4) created at http://localhost:8000/node/120
    18-Feb-21 09:20:17 - INFO - {'type': [{'target_id': 'islandora_object', 'target_type': 'node_type'}], 'title': [{'value': 'California School for the Deaf Response to CA Library Inventory Survey, page 1'}], 'status': [{'value': 1}], 'field_model': [{'target_id': 29, 'target_type': 'taxonomy_term'}], 'field_member_of': [{'target_id': '120', 'target_type': 'node'}], 'field_weight': [{'value': '1'}], 'field_display_hints': [{'target_id': 'Open Seadragon', 'target_type': 'taxonomy_term'}]}
    18-Feb-21 09:20:17 - WARNING - Node for page "4_002-2-b-01-17-08_001-001" not created, HTTP response code was 422.

It seems like the JSON output of the csv?

**Comment by zvowell** [comment]
tried again with a fresh VM, and still received the same Warning messages for the page nodes. I also adjusted the max upload size and max post size in php.ini to 500 MB, and made sure I could manually create paged content, just to make sure it wasn't an obvious general system issue that was preventing the page nodes from being created.

**Comment by mjordan** [comment]
If you try to use Workbench to create those pages not as children but as top-level objects, what happens?

**Comment by mjordan** [comment]
Or, if you want to package up everything into a zip and send it to me (I can provide an upload URL) I can try with your files.

**Comment by mjordan** [comment]
> It seems like the JSON output of the csv?

Yes, when it creates nodes, Workbench converts the CSV data into the JSON structure that Drupal's REST API expects.

**Comment by zvowell** [comment]
I was able to use Workbench to create one set of pages as nodes with an Image model (is that what you meant by top-level object?), and the TIFFs seemed to upload okay and generate derivatives. Config was:
    
    task: create
    host: "http://localhost:8000"
    username: admin
    password: islandora
    input_dir: testBatch_02_clean/6
    input_csv: barneberg_forTesting_004_bookObjects-as-imageObjects.csv
    allow_adding_terms: true

And csv is here: https://gist.github.com/zvowell/66e89b157e03bc12b020e0447b324a5b

If you wouldn't mind trying it on your end, that'd be great, thank you!!  I can gather everything together in a zip whenever you're ready (no rush). And thanks for the clarification on the JSON. Good to know.

**Comment by mjordan** [comment]
> create one set of pages as nodes with an Image model 

Yes, thanks, that eliminates one set of variables.

I can take the zip any time. Are you on the Islandora Slack, if so, dm me and I'll provide an upload URL for he zip.

Thanks for working through this - I'd love to find out why those page nodes are failing.

**Comment by mjordan** [comment]
@zvowell  Using your data I was able to ingest all of the page nodes and accompanying TIFFs. I have no idea why. I did modify your CSV since it contained some fields that weren't configured in my Vagrant. I am attaching it here in case you want to try using it.


[barneberg_forTesting_004_bookObjects-minimal.csv.txt](https://github.com/mjordan/islandora_workbench/files/6026890/barneberg_forTesting_004_bookObjects-minimal.csv.txt)

**Comment by zvowell** [comment]
I tried using the modified csv, and still received the 422 errors for the page nodes. 

Not sure if this is related, but I actually tried it 3 different ways:

1. As-is, downloaded from your link
2. Adding a field_display_hints column to the csv, and populating it with "Open Seadragon" for every record
3. Using the same csv as #1, and adding "paged_content_page_display_hints = 2" to the config file

For #1 and #3, I received this error:

    Node for "Letter from Shepherd to Barneberg, March 10, 1927" (record 3) created at http://localhost:8000/node/73.
    Traceback (most recent call last):
      File "./workbench", line 963, in <module>
        create()
      File "./workbench", line 357, in create
        create_children_from_directory(
      File "/mnt/c/Users/zvowell/Documents/islandora_workbench/workbench_utils.py", line 2646, in create_children_from_directory
        {'target_id': parent_csv_record['field_display_hints'],
    KeyError: 'field_display_hints'

I include this error here just in case it helps anything, really. It was easy enough to fix by following the method in bullet point #2 (and that's how I had it set up on the csv I sent you). 

I think I'll make this a priority to test with an actual installation (rather than a VM). Not sure when that will be, but I'll update this issue with any results from that. Thanks for testing it out on your end!

**Comment by mjordan** [comment]
WRT the `field_display_hints` error, I fixed that this morning (https://github.com/mjordan/islandora_workbench/issues/231). Can you pull in the latest from `main` and try that again?

**Comment by zvowell** [comment]
well, well! After the update, the TIFFs are now being added as media to the child page nodes. When I first tried it after the update, with the field_display_hints field still in the csv, the child page nodes got skipped again. But then when I removed that field, the children and their TIFFs were successfully added.

I'll try with more fields now.

One other piece of data: *before* the update, I successfully Paged Content nodes, their children and TIFFs, using the parent_id field.

**Comment by mjordan** [comment]
@zvowell your mention of `field_display_hints` reminds me that I should return to issue #86 and reduce the need for the user to futz with that (unless they want to override the default).

**Comment by zvowell** [comment]
@mjordan yes, that seems like that'd be a good idea, and seems similar to the way Workbench has a default definition for media types based on file extensions (https://mjordan.github.io/islandora_workbench_docs/media_types/). Should I go ahead and close this issue? Sub-directory based ingest seems to be working well now for me.

**Comment by mjordan** [comment]
Yes, thanks, if using subdirectories to create paged content is now working, let's close this one and I'll move on to #86 soon.
